version: "3.3"

services:
  api:
    container_name: chat-service
    build:
      context: .
    restart: always
    depends_on:
      - elasticsearch
      - rabbitmq
      - db
      - redis
    ports:
      - 8000:8000
    environment:
      - ELASTIC_DOMAIN=elasticsearch
      - ELASTIC_PROTOCOL=http
      - ELASTIC_PORT=9200
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=chat
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
    volumes:
     - ./:/app

  db:
    image: mysql:latest
    container_name: chat-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=chat
    volumes:
      - ./:/app

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./:/app
    command: ["redis-server", "--appendonly", "yes"]

  rabbitmq:
    image: rabbitmq:management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672" # RabbitMQ message broker port
      - "15672:15672" # Management console port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./:/app

  consumer:
    container_name: chat-consumer
    build:
      context: .
      dockerfile: Dockerfile_consumer
    restart: always
    depends_on:
      - elasticsearch
      - rabbitmq
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=chat
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - ELASTIC_DOMAIN=elasticsearch
      - ELASTIC_PROTOCOL=http
      - ELASTIC_PORT=9200
    volumes:
     - ./:/app

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g # Adjust heap size as needed
    image: elasticsearch:8.16.1
    ports:
      - 9200:9200
