version: "3.3"

services:
  api:
    container_name: chat-service
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=chat
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
    volumes:
     - ./:/app

  db:
    image: mysql:latest
    container_name: chat-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=chat
    volumes:
      - ./:/app
  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./:/app
    command: ["redis-server", "--appendonly", "yes"]