"""add indices

Revision ID: 3ccee1a94b14
Revises: 5afc1a74691c
Create Date: 2024-11-24 18:40:58.073527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccee1a94b14'
down_revision: Union[str, None] = '5afc1a74691c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_app_token'), 'chats', ['app_token'], unique=False)
    op.create_index(op.f('ix_chats_number'), 'chats', ['number'], unique=False)
    op.create_unique_constraint('uq_app_token_number', 'chats', ['app_token', 'number'])
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_unique_constraint('uq_chat_id_number', 'messages', ['chat_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_id_number', 'messages', type_='unique')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_constraint('uq_app_token_number', 'chats', type_='unique')
    op.drop_index(op.f('ix_chats_number'), table_name='chats')
    op.drop_index(op.f('ix_chats_app_token'), table_name='chats')
    # ### end Alembic commands ###
