"""add chats_count col

Revision ID: 5afc1a74691c
Revises: e89cd77073fd
Create Date: 2024-11-24 17:32:58.137000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afc1a74691c'
down_revision: Union[str, None] = 'e89cd77073fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('chats_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'chats_count')
    # ### end Alembic commands ###
